server:
  port: 9000
  servlet:
    context-path: /airbus-web

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://***:5432/airbus
    username: postgres
    password: airbus!2022
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
